name: docs

on:
  workflow_dispatch:
  release:
    types: [created]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  packages: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo  
      uses: actions/checkout@v6
    - name: Install the latest version of uv and set the python version
      uses: astral-sh/setup-uv@v7
    - name: prepare
      run: cp ./README.md ./docs/.
    - name: Install needed packages
      run: uv add mkdocs "mkdocstrings[python]" --dev
    - name: build the docs
      run: uv run mkdocs build
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: './site'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
