name: Test
on:
  push:

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version:  ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade --upgrade-strategy eager -r requirements_dev.txt
    - name: Install actual package
      run: |
        pip install -e .
    - name: Run tests
      run: coverage run -m pytest -v
    - name: Create Coverage Report
      run: coverage xml
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
        verbose: true
